### ISSUE TITLE
Pretrained checkpoint

### ISSUE THREAD

**Issue by wingrune** [Mr-Neko/NICE#1]
Hello! Thank you for amazing work. I would like to ask several questions. Are you planning to release a pretrained checkpoint for your model? Does this repository correspond to the paper "Towards Real-Time Panoptic Narrative Grounding by an End-to-End Grounding Network"?

**Comment by Mr-Neko** [comment]
Thank you! I forget to upload the checkpoint, it will be updated in few days! :sob: As for the EPNG, the NICE framework includes the training of EPNG with the pretrained Panoptic FPN and detectron2. You can also use the previous code with customized backbone settings.

**Comment by Mr-Neko** [comment]
The checkpoint is uploaded! Please follow the README.md to test it. @wingrune
