### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by wingrune** [Mr-Neko/NICE#2]
Hello! Thank you for providing the pre-trained checkpoints. I would like to ask a question about the model inference time. Does the inference time of EPNG mentioned in the article include visual and text features computation? I've tested the checkpoints provided for NICE on the RTX 3060 GPU and have got that the whole pipeline takes around 140 ms per image with 100 ms needed for FPN feature and text embedding computation. Is it something that would be expected?

**Comment by Mr-Neko** [comment]
The inference of visual and language backbone are computed. I think there are mainly three reasons for the results.

1. We test our models on A100, which is different with the 3060.
2. The results of EPNG is the inference of per phrase. You should take the 140ms per image divided about 5.5 (according to the PNG)
3. The resolution of image in NICE is two times as much as EPNG, which will cost more time to inference.

Wish it can help you! :smiling_face_with_three_hearts:

**Comment by wingrune** [comment]
It is much clearer now, thank you for your answer!
